### ISSUE TITLE
Define and create a homescreen for non logged in users.

### ISSUE THREAD

**Issue by HarryET** [HarryET/github-chat#14]
We need to decide what todo when a user isn't logged in. We could just redirect to the login screen or we could show no chats/most popular public chats with random messages?

Currently this just throws errors as the session uuid is null.

**Comment by hugo-cardenas** [comment]
Non-logged in users are now redirected always to login screen.

We could improve this by redirecting non-logged users to a homescreen with some valuable information which would incentivize them to log in.

E.g. some feed of existing public chats & messages.
