### ISSUE TITLE
Making a chat room private

### ISSUE THREAD

**Issue by Sicily-F** [HarryET/github-chat#65]
Hi there,

I'm wondering if it is possible to make a chat room private at all? My repository is public, but I'd like to make a private chat room for people to ask questions in that couldn't just be found by anyone. This is largely for parts of my research where participants may wish to remain anonymous.

**Comment by HarryET** [comment]
Hey @Sicily-F, this project has been left for now. I will revisit it soon if and when I get the chance...

**Comment by Sicily-F** [comment]
Hi Harry - ok thank you for your response!

**Comment by HarryET** [comment]
If there is still an active interest in the project I can revisit it but to me knowledge there are no active users.

**Comment by HarryET** [comment]
Hey @Sicily-F, I'm closing this for now. Feel free to re-open this issue or a new issue with any other questions
